" set up pathogen, https://github.com/tpope/vim-pathogen
filetype off
call pathogen#infect()
filetype plugin indent on

" don't bother with vi compatibility
set nocompatible

" enable syntax highlighting
syntax enable

" enable 256 colors
set t_Co=256

" show line numbers
set number

" keyboard shortcuts
let mapleader = ','
nmap <leader>b :CtrlPBuffer<CR>
nmap <leader>d :NERDTreeToggle<CR>
nmap <leader>f :NERDTreeFind<CR>
nmap <leader>t :TagbarToggle<CR>
nmap <leader>p :CtrlP<CR>
nmap <leader>. :CtrlPTag<cr>
nmap <leader>l :setlocal number!<CR>
nmap <leader>o :set paste!<CR>
" quickly navigate between buffers
nmap <C-e> :e#<CR>
nmap <C-n> :bnext<CR>
nmap <C-p> :bprev<CR>
" disable moving cursor around using arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
" Make dealing with split windows a little easier
set equalalways " Vertical and horizontal splits default to equal sizes when created
set splitbelow splitright
:noremap <leader>v :vsp<cr> " Quick access to vertical splits
:noremap <leader>h :split<cr> " Quick access to horizontal splits
:noremap <leader>w :wincmd w<cr> " Cycle through windows
" Smart way to move btw. windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
" plugin settings
let g:ctrlp_match_window = 'order:ttb,max:20'
let g:ctrlp_map = '<c-p>'
let g:NERDSpaceDelims=1
" vim-airline doesn't appear until I create a new split
set laststatus=2
